174,0
S,ConstructRing,Returns the full weighted polynomial ring,0,1,0,0,0,0,0,0,0,457,,-1,-38,-38,-38,-38,-38
S,ConstructIdeal,Returns the ideal I determined by the relations,0,2,0,0,0,0,0,0,0,457,,0,0,64,,-1,-38,-38,-38,-38,-38
S,RelationstoPolynomials,Contructs polynomials from the relations,0,3,0,0,0,0,0,0,0,148,,0,0,82,,0,0,64,,-1,-38,-38,-38,-38,-38
S,EvaluateMonomials,For a given set of HMF this produces all multiples with weight k,1,1,1,82,0,63,2,0,0,0,0,0,0,0,82,,0,0,457,,-1,-38,-38,-38,-38,-38
S,MonomialGenerators,Returns Generators for the weight k monomials in R/I,0,3,0,0,0,0,0,0,0,148,,0,0,457,,0,0,64,,-1,-38,-38,-38,-38,-38
S,FindNewGenerators,Constructs generators for the complement of the subspace generated by multiplication from lower weights,0,5,0,0,0,0,0,0,0,82,,0,0,82,,0,0,148,,0,0,217,,0,0,ModFrmHilD,,-1,-38,-38,-38,-38,-38
S,ConstructGeneratorsAndRelations,Finds all Generators and Relations,0,4,0,0,0,0,0,0,0,148,,0,0,148,,0,0,217,,0,0,ModFrmHilD,,-1,-38,-38,-38,-38,-38
S,ConstructGeneratorsAndRelationsSymmetric,Finds all Generators and Relations,0,4,0,0,0,0,0,0,0,148,,0,0,148,,0,0,217,,0,0,ModFrmHilD,,-1,-38,-38,-38,-38,-38
S,Relations,Finds all Generators and Relations,0,4,0,0,0,0,0,0,0,148,,0,0,457,,0,0,457,,0,0,ModFrmHilD,,-1,-38,-38,-38,-38,-38
S,QuadSpace,Easy way to produces a quadratic space with Driscriminant D and precision prec,0,2,0,0,0,0,0,0,0,148,,0,0,148,,-1,-38,-38,-38,-38,-38
S,MakeScheme,Returns the Scheme,0,2,0,0,0,0,0,0,0,457,,0,0,457,,-1,-38,-38,-38,-38,-38
S,MakeHilbertSeries,Returns Hilbert series with precision n,0,3,0,0,0,0,0,0,0,148,,0,0,457,,0,0,457,,-1,-38,-38,-38,-38,-38
